spring:
  datasource:
    url: jdbc:mysql://120.26.184.107:3306/shop
    username: root
    password: Zheng1125
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    # 邮件服务地址
    host: smtp.qq.com
    # 端口
    port: 587
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: zjqq520@vip.qq.com
    # 授权码
    password: trzxocmignokfacc
    # 其它参数
    properties:
      mail:
        smtp:
          # 如果是用 SSL 方式，需要配置如下属性
          starttls:
            enable: true
            required: true

